import { _mock } from 'src/_mock';

// ----------------------------------------------------------------------

export const countries = [
  {
    name: 'Aruba',
    code: 'AW',
    capital: 'Oranjestad',
    latlng: [12.5, -69.96666666],
    timezones: ['America/Aruba'],
    photoUrl: _mock.image.cover(1),
  },
  {
    name: 'Afghanistan',
    code: 'AF',
    capital: 'Kabul',
    latlng: [33, 65],
    timezones: ['Asia/Kabul'],
    photoUrl: _mock.image.cover(2),
  },
  {
    name: 'Angola',
    code: 'AO',
    capital: 'Luanda',
    latlng: [-12.5, 18.5],
    timezones: ['Africa/Luanda'],
    photoUrl: _mock.image.cover(3),
  },
  {
    name: 'Vanuatu',
    code: 'VU',
    capital: 'Port Vila',
    latlng: [-16, 167],
    timezones: ['Pacific/Efate'],
    photoUrl: _mock.image.cover(4),
  },
  {
    name: 'Wallis and Futuna',
    code: 'WF',
    capital: 'Mata-Utu',
    latlng: [-13.3, -176.2],
    timezones: ['Pacific/Wallis'],
    photoUrl: _mock.image.cover(5),
  },
  {
    name: 'Samoa',
    code: 'WS',
    capital: 'Apia',
    latlng: [-13.58333333, -172.33333333],
    timezones: ['Pacific/Apia'],
    photoUrl: _mock.image.cover(6),
  },
  {
    name: 'Yemen',
    code: 'YE',
    capital: "Sana'a",
    latlng: [15, 48],
    timezones: ['Asia/Aden'],
    photoUrl: _mock.image.cover(7),
  },
  {
    name: 'South Africa',
    code: 'ZA',
    capital: 'Pretoria',
    latlng: [-29, 24],
    timezones: ['Africa/Johannesburg'],
    photoUrl: _mock.image.cover(8),
  },
  {
    name: 'Zambia',
    code: 'ZM',
    capital: 'Lusaka',
    latlng: [-15, 30],
    timezones: ['Africa/Lusaka'],
    photoUrl: _mock.image.cover(9),
  },
  {
    name: 'Zimbabwe',
    code: 'ZW',
    capital: 'Harare',
    latlng: [-20, 30],
    timezones: ['Africa/Harare'],
    photoUrl: _mock.image.cover(10),
  },
];
// ----------------------------------------------------------------------

export const cities = [
  { city: 'New York', state: 'New York', latitude: 40.6643, longitude: -73.9385 },
  { city: 'Los Angeles', state: 'California', latitude: 34.0194, longitude: -118.4108 },
  { city: 'Chicago', state: 'Illinois', latitude: 41.8376, longitude: -87.6818 },
  { city: 'Houston', state: 'Texas', latitude: 29.7805, longitude: -95.3863 },
  { city: 'Phoenix', state: 'Arizona', latitude: 33.5722, longitude: -112.088 },
  { city: 'Philadelphia', state: 'Pennsylvania', latitude: 40.0094, longitude: -75.1333 },
  { city: 'San Antonio', state: 'Texas', latitude: 29.4724, longitude: -98.5251 },
  { city: 'San Diego', state: 'California', latitude: 32.8153, longitude: -117.135 },
  { city: 'Dallas', state: 'Texas', latitude: 32.7757, longitude: -96.7967 },
  { city: 'San Jose', state: 'California', latitude: 37.2969, longitude: -121.8193 },
  { city: 'Austin', state: 'Texas', latitude: 30.3072, longitude: -97.756 },
  { city: 'Jacksonville', state: 'Florida', latitude: 30.337, longitude: -81.6613 },
  { city: 'San Francisco', state: 'California', latitude: 37.7751, longitude: -122.4193 },
  { city: 'Columbus', state: 'Ohio', latitude: 39.9848, longitude: -82.985 },
  { city: 'Indianapolis', state: 'Indiana', latitude: 39.7767, longitude: -86.1459 },
  { city: 'Fort Worth', state: 'Texas', latitude: 32.7795, longitude: -97.3463 },
  { city: 'Charlotte', state: 'North Carolina', latitude: 35.2087, longitude: -80.8307 },
  { city: 'Seattle', state: 'Washington', latitude: 47.6205, longitude: -122.3509 },
  { city: 'Denver', state: 'Colorado', latitude: 39.7618, longitude: -104.8806 },
  { city: 'El Paso', state: 'Texas', latitude: 31.8484, longitude: -106.427 },
];
