use super::ApiDefinition;

pub const RBAC_APIS: &[ApiDefinition] = &[
    ApiDefinition {
        code: "roles_read",
        method: "GET",
        path_pattern: "/api/rbac/roles",
        name: "List roles",
        group: "RBAC",
    },
    ApiDefinition {
        code: "roles_create",
        method: "POST",
        path_pattern: "/api/rbac/roles",
        name: "Create role",
        group: "RBAC",
    },
    ApiDefinition {
        code: "roles_update",
        method: "PUT",
        path_pattern: "/api/rbac/roles/{code}",
        name: "Update role",
        group: "RBAC",
    },
    ApiDefinition {
        code: "roles_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/roles/{code}",
        name: "Delete role",
        group: "RBAC",
    },
    ApiDefinition {
        code: "menu_item_apis_read",
        method: "GET",
        path_pattern: "/api/rbac/menu-items/{id}/apis",
        name: "Read menu API bindings",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_item_apis_update",
        method: "PUT",
        path_pattern: "/api/rbac/menu-items/{id}/apis",
        name: "Update menu API bindings",
        group: "Menus",
    },
    ApiDefinition {
        code: "role_permissions_read",
        method: "GET",
        path_pattern: "/api/rbac/roles/{code}/permissions",
        name: "Read role permissions",
        group: "RBAC",
    },
    ApiDefinition {
        code: "role_permissions_update",
        method: "PUT",
        path_pattern: "/api/rbac/roles/{code}/permissions",
        name: "Update role permissions",
        group: "RBAC",
    },
    ApiDefinition {
        code: "api_menus_read",
        method: "GET",
        path_pattern: "/api/rbac/apis/{id}/menus",
        name: "Read API menu bindings",
        group: "RBAC",
    },
    ApiDefinition {
        code: "api_menus_update",
        method: "PUT",
        path_pattern: "/api/rbac/apis/{id}/menus",
        name: "Update API menu bindings",
        group: "RBAC",
    },
    ApiDefinition {
        code: "apis_read",
        method: "GET",
        path_pattern: "/api/rbac/apis",
        name: "List API permissions",
        group: "RBAC",
    },
    ApiDefinition {
        code: "apis_unbound_read",
        method: "GET",
        path_pattern: "/api/rbac/apis/unbound",
        name: "List non-menu API permissions",
        group: "RBAC",
    },
    ApiDefinition {
        code: "apis_create",
        method: "POST",
        path_pattern: "/api/rbac/apis",
        name: "Create API permission",
        group: "RBAC",
    },
    ApiDefinition {
        code: "apis_update",
        method: "PUT",
        path_pattern: "/api/rbac/apis/{id}",
        name: "Update API permission",
        group: "RBAC",
    },
    ApiDefinition {
        code: "apis_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/apis/{id}",
        name: "Delete API permission",
        group: "RBAC",
    },
    ApiDefinition {
        code: "menu_sections_read",
        method: "GET",
        path_pattern: "/api/rbac/menu-sections",
        name: "List menu sections",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_sections_create",
        method: "POST",
        path_pattern: "/api/rbac/menu-sections",
        name: "Create menu section",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_sections_update",
        method: "PUT",
        path_pattern: "/api/rbac/menu-sections/{id}",
        name: "Update menu section",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_sections_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/menu-sections/{id}",
        name: "Delete menu section",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_items_read",
        method: "GET",
        path_pattern: "/api/rbac/menu-items",
        name: "List menu items",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_items_create",
        method: "POST",
        path_pattern: "/api/rbac/menu-items",
        name: "Create menu item",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_items_update",
        method: "PUT",
        path_pattern: "/api/rbac/menu-items/{id}",
        name: "Update menu item",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_items_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/menu-items/{id}",
        name: "Delete menu item",
        group: "Menus",
    },
];
