use super::ApiDefinition;

pub const RBAC_APIS: &[ApiDefinition] = &[
    ApiDefinition {
        code: "roles_read",
        method: "GET",
        path_pattern: "/api/rbac/roles",
        name: "角色列表",
    },
    ApiDefinition {
        code: "roles_create",
        method: "POST",
        path_pattern: "/api/rbac/roles",
        name: "创建角色",
    },
    ApiDefinition {
        code: "roles_update",
        method: "PUT",
        path_pattern: "/api/rbac/roles/{code}",
        name: "更新角色",
    },
    ApiDefinition {
        code: "roles_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/roles/{code}",
        name: "删除角色",
    },
    ApiDefinition {
        code: "menu_item_apis_read",
        method: "GET",
        path_pattern: "/api/rbac/menu-items/{id}/apis",
        name: "读取菜单API绑定",
    },
    ApiDefinition {
        code: "menu_item_apis_update",
        method: "PUT",
        path_pattern: "/api/rbac/menu-items/{id}/apis",
        name: "更新菜单API绑定",
    },
    ApiDefinition {
        code: "role_permissions_read",
        method: "GET",
        path_pattern: "/api/rbac/roles/{code}/permissions",
        name: "读取角色权限",
    },
    ApiDefinition {
        code: "role_permissions_update",
        method: "PUT",
        path_pattern: "/api/rbac/roles/{code}/permissions",
        name: "更新角色权限",
    },
    ApiDefinition {
        code: "api_menus_read",
        method: "GET",
        path_pattern: "/api/rbac/apis/{id}/menus",
        name: "读取API菜单绑定",
    },
    ApiDefinition {
        code: "api_menus_update",
        method: "PUT",
        path_pattern: "/api/rbac/apis/{id}/menus",
        name: "更新API菜单绑定",
    },
    ApiDefinition {
        code: "apis_read",
        method: "GET",
        path_pattern: "/api/rbac/apis",
        name: "API权限列表",
    },
    ApiDefinition {
        code: "apis_unbound_read",
        method: "GET",
        path_pattern: "/api/rbac/apis/unbound",
        name: "未绑定菜单API列表",
    },
    ApiDefinition {
        code: "apis_create",
        method: "POST",
        path_pattern: "/api/rbac/apis",
        name: "创建API权限",
    },
    ApiDefinition {
        code: "apis_update",
        method: "PUT",
        path_pattern: "/api/rbac/apis/{id}",
        name: "更新API权限",
    },
    ApiDefinition {
        code: "apis_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/apis/{id}",
        name: "删除API权限",
    },
    ApiDefinition {
        code: "menu_sections_read",
        method: "GET",
        path_pattern: "/api/rbac/menu-sections",
        name: "菜单分组列表",
    },
    ApiDefinition {
        code: "menu_sections_create",
        method: "POST",
        path_pattern: "/api/rbac/menu-sections",
        name: "创建菜单分组",
    },
    ApiDefinition {
        code: "menu_sections_update",
        method: "PUT",
        path_pattern: "/api/rbac/menu-sections/{id}",
        name: "更新菜单分组",
    },
    ApiDefinition {
        code: "menu_sections_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/menu-sections/{id}",
        name: "删除菜单分组",
    },
    ApiDefinition {
        code: "menu_items_read",
        method: "GET",
        path_pattern: "/api/rbac/menu-items",
        name: "菜单列表",
    },
    ApiDefinition {
        code: "menu_items_create",
        method: "POST",
        path_pattern: "/api/rbac/menu-items",
        name: "创建菜单",
    },
    ApiDefinition {
        code: "menu_items_update",
        method: "PUT",
        path_pattern: "/api/rbac/menu-items/{id}",
        name: "更新菜单",
    },
    ApiDefinition {
        code: "menu_items_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/menu-items/{id}",
        name: "删除菜单",
    },
];
