use super::ApiDefinition;

pub const USER_APIS: &[ApiDefinition] = &[
    ApiDefinition {
        code: "account_profile_read",
        method: "GET",
        path_pattern: "/api/account/profile",
        name: "个人资料",
    },
    ApiDefinition {
        code: "account_password_email_code",
        method: "POST",
        path_pattern: "/api/account/password/email-code",
        name: "发送账户改密邮箱验证码",
    },
    ApiDefinition {
        code: "account_password_change",
        method: "POST",
        path_pattern: "/api/account/password/change",
        name: "修改账户密码",
    },
    ApiDefinition {
        code: "account_verify_email",
        method: "POST",
        path_pattern: "/api/account/email/verify",
        name: "验证账户邮箱",
    },
    ApiDefinition {
        code: "account_identities_read",
        method: "GET",
        path_pattern: "/api/account/identities",
        name: "账户登录 Provider 列表",
    },
    ApiDefinition {
        code: "account_identity_delete",
        method: "DELETE",
        path_pattern: "/api/account/identities/{identity_id}",
        name: "解绑账户登录 Provider",
    },
    ApiDefinition {
        code: "account_oauth_start",
        method: "GET",
        path_pattern: "/api/account/oauth/{provider}/start",
        name: "账户 OAuth 绑定开始",
    },
    ApiDefinition {
        code: "account_oauth_callback",
        method: "GET",
        path_pattern: "/api/account/oauth/{provider}/callback",
        name: "账户 OAuth 绑定回调",
    },
    ApiDefinition {
        code: "account_wallet_link",
        method: "POST",
        path_pattern: "/api/account/wallet/link",
        name: "绑定账户钱包",
    },
    ApiDefinition {
        code: "account_affiliate_summary_read",
        method: "GET",
        path_pattern: "/api/account/affiliate-summary",
        name: "返佣中心概览",
    },
    ApiDefinition {
        code: "account_affiliate_referrals_read",
        method: "GET",
        path_pattern: "/api/account/affiliate/referrals",
        name: "返佣中心邀请用户",
    },
    ApiDefinition {
        code: "account_affiliate_commissions_read",
        method: "GET",
        path_pattern: "/api/account/affiliate/commissions",
        name: "返佣中心返佣记录",
    },
    ApiDefinition {
        code: "account_affiliate_commissions_export",
        method: "GET",
        path_pattern: "/api/account/affiliate/commissions/export",
        name: "导出个人返佣记录",
    },
    ApiDefinition {
        code: "users_read",
        method: "GET",
        path_pattern: "/api/users",
        name: "用户列表",
    },
    ApiDefinition {
        code: "users_create",
        method: "POST",
        path_pattern: "/api/users",
        name: "创建用户",
    },
    ApiDefinition {
        code: "users_detail",
        method: "GET",
        path_pattern: "/api/users/{id}",
        name: "用户详情",
    },
    ApiDefinition {
        code: "users_update",
        method: "PUT",
        path_pattern: "/api/users/{id}",
        name: "更新用户",
    },
    ApiDefinition {
        code: "users_delete",
        method: "DELETE",
        path_pattern: "/api/users/{id}",
        name: "删除用户",
    },
    ApiDefinition {
        code: "users_identity_delete",
        method: "DELETE",
        path_pattern: "/api/users/{id}/identities/{identity_id}",
        name: "解绑用户登录 Provider",
    },
    ApiDefinition {
        code: "user_groups_read",
        method: "GET",
        path_pattern: "/api/admin/user-groups",
        name: "用户分组列表",
    },
    ApiDefinition {
        code: "user_groups_create",
        method: "POST",
        path_pattern: "/api/admin/user-groups",
        name: "创建用户分组",
    },
    ApiDefinition {
        code: "user_groups_detail",
        method: "GET",
        path_pattern: "/api/admin/user-groups/{code}",
        name: "用户分组详情",
    },
    ApiDefinition {
        code: "user_groups_update",
        method: "PATCH",
        path_pattern: "/api/admin/user-groups/{code}",
        name: "更新用户分组",
    },
    ApiDefinition {
        code: "user_groups_delete",
        method: "DELETE",
        path_pattern: "/api/admin/user-groups/{code}",
        name: "删除用户分组",
    },
    ApiDefinition {
        code: "user_groups_members_read",
        method: "GET",
        path_pattern: "/api/admin/user-groups/{code}/users",
        name: "用户分组成员",
    },
];
