pub struct ApiDefinition {
    pub code: &'static str,
    pub method: &'static str,
    pub path_pattern: &'static str,
    pub name: &'static str,
    pub group: &'static str,
}

pub const API_DEFINITIONS: &[ApiDefinition] = &[
    ApiDefinition {
        code: "auth_me",
        method: "GET",
        path_pattern: "/api/auth/me",
        name: "Current user",
        group: "Auth",
    },
    ApiDefinition {
        code: "navbar_read",
        method: "GET",
        path_pattern: "/api/navbar",
        name: "Navbar",
        group: "System",
    },
    ApiDefinition {
        code: "users_read",
        method: "GET",
        path_pattern: "/api/users",
        name: "List users",
        group: "Users",
    },
    ApiDefinition {
        code: "users_create",
        method: "POST",
        path_pattern: "/api/users",
        name: "Create user",
        group: "Users",
    },
    ApiDefinition {
        code: "users_update",
        method: "PUT",
        path_pattern: "/api/users/{id}",
        name: "Update user",
        group: "Users",
    },
    ApiDefinition {
        code: "users_delete",
        method: "DELETE",
        path_pattern: "/api/users/{id}",
        name: "Delete user",
        group: "Users",
    },
    ApiDefinition {
        code: "roles_read",
        method: "GET",
        path_pattern: "/api/rbac/roles",
        name: "List roles",
        group: "RBAC",
    },
    ApiDefinition {
        code: "roles_create",
        method: "POST",
        path_pattern: "/api/rbac/roles",
        name: "Create role",
        group: "RBAC",
    },
    ApiDefinition {
        code: "roles_update",
        method: "PUT",
        path_pattern: "/api/rbac/roles/{code}",
        name: "Update role",
        group: "RBAC",
    },
    ApiDefinition {
        code: "roles_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/roles/{code}",
        name: "Delete role",
        group: "RBAC",
    },
    ApiDefinition {
        code: "role_apis_read",
        method: "GET",
        path_pattern: "/api/rbac/roles/{code}/apis",
        name: "Read role API bindings",
        group: "RBAC",
    },
    ApiDefinition {
        code: "role_apis_update",
        method: "PUT",
        path_pattern: "/api/rbac/roles/{code}/apis",
        name: "Update role API bindings",
        group: "RBAC",
    },
    ApiDefinition {
        code: "role_menus_read",
        method: "GET",
        path_pattern: "/api/rbac/roles/{code}/menus",
        name: "Read role menu bindings",
        group: "RBAC",
    },
    ApiDefinition {
        code: "role_menus_update",
        method: "PUT",
        path_pattern: "/api/rbac/roles/{code}/menus",
        name: "Update role menu bindings",
        group: "RBAC",
    },
    ApiDefinition {
        code: "apis_read",
        method: "GET",
        path_pattern: "/api/rbac/apis",
        name: "List API permissions",
        group: "RBAC",
    },
    ApiDefinition {
        code: "apis_create",
        method: "POST",
        path_pattern: "/api/rbac/apis",
        name: "Create API permission",
        group: "RBAC",
    },
    ApiDefinition {
        code: "apis_update",
        method: "PUT",
        path_pattern: "/api/rbac/apis/{id}",
        name: "Update API permission",
        group: "RBAC",
    },
    ApiDefinition {
        code: "apis_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/apis/{id}",
        name: "Delete API permission",
        group: "RBAC",
    },
    ApiDefinition {
        code: "menu_sections_read",
        method: "GET",
        path_pattern: "/api/rbac/menu-sections",
        name: "List menu sections",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_sections_create",
        method: "POST",
        path_pattern: "/api/rbac/menu-sections",
        name: "Create menu section",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_sections_update",
        method: "PUT",
        path_pattern: "/api/rbac/menu-sections/{id}",
        name: "Update menu section",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_sections_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/menu-sections/{id}",
        name: "Delete menu section",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_items_read",
        method: "GET",
        path_pattern: "/api/rbac/menu-items",
        name: "List menu items",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_items_create",
        method: "POST",
        path_pattern: "/api/rbac/menu-items",
        name: "Create menu item",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_items_update",
        method: "PUT",
        path_pattern: "/api/rbac/menu-items/{id}",
        name: "Update menu item",
        group: "Menus",
    },
    ApiDefinition {
        code: "menu_items_delete",
        method: "DELETE",
        path_pattern: "/api/rbac/menu-items/{id}",
        name: "Delete menu item",
        group: "Menus",
    },
    ApiDefinition {
        code: "models_global_read",
        method: "GET",
        path_pattern: "/api/admin/models/global",
        name: "List global models",
        group: "Models",
    },
    ApiDefinition {
        code: "models_global_create",
        method: "POST",
        path_pattern: "/api/admin/models/global",
        name: "Create global model",
        group: "Models",
    },
    ApiDefinition {
        code: "models_global_detail",
        method: "GET",
        path_pattern: "/api/admin/models/global/{id}",
        name: "Get global model",
        group: "Models",
    },
    ApiDefinition {
        code: "models_global_update",
        method: "PATCH",
        path_pattern: "/api/admin/models/global/{id}",
        name: "Update global model",
        group: "Models",
    },
    ApiDefinition {
        code: "models_global_delete",
        method: "DELETE",
        path_pattern: "/api/admin/models/global/{id}",
        name: "Delete global model",
        group: "Models",
    },
    ApiDefinition {
        code: "models_global_batch_delete",
        method: "POST",
        path_pattern: "/api/admin/models/global/batch-delete",
        name: "Batch delete global models",
        group: "Models",
    },
    ApiDefinition {
        code: "models_global_providers",
        method: "GET",
        path_pattern: "/api/admin/models/global/{id}/providers",
        name: "Global model providers",
        group: "Models",
    },
    ApiDefinition {
        code: "models_catalog_read",
        method: "GET",
        path_pattern: "/api/admin/models/catalog",
        name: "Model catalog",
        group: "Models",
    },
    ApiDefinition {
        code: "wallet_balance_read",
        method: "GET",
        path_pattern: "/api/wallet/balance",
        name: "Wallet balance",
        group: "Wallet",
    },
    ApiDefinition {
        code: "wallet_transactions_read",
        method: "GET",
        path_pattern: "/api/wallet/transactions",
        name: "Wallet transactions",
        group: "Wallet",
    },
    ApiDefinition {
        code: "models_public_catalog_read",
        method: "GET",
        path_pattern: "/api/models/catalog",
        name: "Public model catalog",
        group: "Models",
    },
    ApiDefinition {
        code: "models_external_read",
        method: "GET",
        path_pattern: "/api/admin/models/external",
        name: "External models",
        group: "Models",
    },
];
