use rust_decimal::Decimal;
use types::provider::{RequestRecord, UsageRecord};

use crate::{StorageResult, provider::record::RequestRecordSummaryRecord};

use super::{
    request_record_detail::format_timestamp,
    request_record_summary::DEFAULT_COST_CURRENCY,
    request_upstream_cost::{self, StoredUpstreamCost},
};

pub(super) fn usage_record(record: RequestRecordSummaryRecord) -> UsageRecord {
    UsageRecord {
        created_at: format_timestamp(record.created_at),
        token_name: record.token_name_snapshot,
        token_prefix: record.token_prefix_snapshot,
        model_name: record.model_name_snapshot.or(record.global_model_id),
        client_api_format: record.client_api_format,
        request_type: record.request_type,
        is_stream: record.is_stream,
        status: record.status,
        prompt_tokens: record.prompt_tokens,
        completion_tokens: record.completion_tokens,
        total_tokens: record.total_tokens,
        cache_creation_input_tokens: record.cache_creation_input_tokens,
        cache_read_input_tokens: record.cache_read_input_tokens,
        total_cost: record.total_cost.unwrap_or(Decimal::ZERO),
        cost_currency: record.cost_currency.unwrap_or_else(|| DEFAULT_COST_CURRENCY.into()),
        response_headers_time_ms: record.response_headers_time_ms,
        first_sse_event_time_ms: record.first_sse_event_time_ms,
        first_token_time_ms: record.first_token_time_ms,
        first_byte_time_ms: record.first_byte_time_ms,
        total_latency_ms: record.total_latency_ms,
    }
}

pub(super) fn summary_record(record: RequestRecordSummaryRecord) -> StorageResult<RequestRecord> {
    let upstream_cost = request_upstream_cost::response(StoredUpstreamCost::from_request_record(&record))?;
    Ok(RequestRecord {
        request_id: record.request_id,
        created_at: format_timestamp(record.created_at),
        user_id: record.user_id_snapshot,
        username: record.username_snapshot,
        token_id: record.token_id,
        token_name: record.token_name_snapshot,
        token_prefix: record.token_prefix_snapshot,
        group_code: record.group_code,
        global_model_id: record.global_model_id.clone(),
        model_name: record.model_name_snapshot.or(record.global_model_id),
        provider_id: record.provider_id,
        provider_name: record.provider_name_snapshot,
        provider_key_name: record.provider_key_name_snapshot,
        provider_key_preview: record.provider_key_preview_snapshot,
        client_api_format: record.client_api_format,
        provider_api_format: record.provider_api_format,
        request_type: record.request_type,
        is_stream: record.is_stream,
        has_failover: record.has_failover,
        has_retry: record.has_retry,
        status: record.status,
        billing_status: record.billing_status,
        client_status_code: record.client_status_code,
        client_error_type: record.client_error_type,
        client_error_message: record.client_error_message,
        termination_origin: record.termination_origin,
        termination_reason: record.termination_reason,
        stream_end_reason: record.stream_end_reason,
        prompt_tokens: record.prompt_tokens,
        completion_tokens: record.completion_tokens,
        total_tokens: record.total_tokens,
        cache_creation_input_tokens: record.cache_creation_input_tokens,
        cache_read_input_tokens: record.cache_read_input_tokens,
        input_text_tokens: record.input_text_tokens,
        input_audio_tokens: record.input_audio_tokens,
        input_image_tokens: record.input_image_tokens,
        output_text_tokens: record.output_text_tokens,
        output_audio_tokens: record.output_audio_tokens,
        output_image_tokens: record.output_image_tokens,
        reasoning_tokens: record.reasoning_tokens,
        cache_creation_5m_input_tokens: record.cache_creation_5m_input_tokens,
        cache_creation_1h_input_tokens: record.cache_creation_1h_input_tokens,
        usage_source: record.usage_source,
        usage_semantic: record.usage_semantic,
        service_tier: record.service_tier,
        upstream_cost,
        input_cost: record.input_cost,
        output_cost: record.output_cost,
        cache_creation_cost: record.cache_creation_cost,
        cache_read_cost: record.cache_read_cost,
        request_cost: record.request_cost,
        input_price_per_million: record.input_price_per_million,
        output_price_per_million: record.output_price_per_million,
        cache_creation_price_per_million: record.cache_creation_price_per_million,
        cache_read_price_per_million: record.cache_read_price_per_million,
        total_cost: record.total_cost.unwrap_or(Decimal::ZERO),
        token_cost: record.token_cost.unwrap_or(Decimal::ZERO),
        base_cost: record.base_cost.unwrap_or(Decimal::ZERO),
        billing_multiplier: record.billing_multiplier.unwrap_or(Decimal::ONE),
        billing_snapshot: crate::json::decode_optional(record.billing_snapshot).ok().flatten(),
        cost_currency: record.cost_currency.unwrap_or_else(|| DEFAULT_COST_CURRENCY.into()),
        response_headers_time_ms: record.response_headers_time_ms,
        first_sse_event_time_ms: record.first_sse_event_time_ms,
        first_token_time_ms: record.first_token_time_ms,
        first_byte_time_ms: record.first_byte_time_ms,
        total_latency_ms: record.total_latency_ms,
        candidate_count: record.candidate_count.try_into().unwrap_or(0),
    })
}
