use rust_decimal::Decimal;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "request_records")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub request_id: String,
    pub token_id: Option<String>,
    pub user_id_snapshot: Option<String>,
    pub username_snapshot: Option<String>,
    pub token_name_snapshot: Option<String>,
    pub token_prefix_snapshot: Option<String>,
    pub group_code: Option<String>,
    pub global_model_id: Option<String>,
    pub model_name_snapshot: Option<String>,
    pub provider_id: Option<String>,
    pub provider_name_snapshot: Option<String>,
    pub endpoint_id: Option<String>,
    pub key_id: Option<String>,
    pub provider_key_name_snapshot: Option<String>,
    pub provider_key_preview_snapshot: Option<String>,
    pub client_api_format: String,
    pub provider_api_format: Option<String>,
    pub request_type: String,
    pub is_stream: bool,
    pub has_failover: bool,
    pub has_retry: bool,
    pub status: String,
    pub billing_status: String,
    pub client_status_code: Option<i32>,
    pub client_error_type: Option<String>,
    pub client_error_message: Option<String>,
    pub termination_origin: Option<String>,
    pub termination_reason: Option<String>,
    pub stream_end_reason: Option<String>,
    pub prompt_tokens: Option<i64>,
    pub completion_tokens: Option<i64>,
    pub total_tokens: Option<i64>,
    pub cache_creation_input_tokens: Option<i64>,
    pub cache_read_input_tokens: Option<i64>,
    pub input_text_tokens: Option<i64>,
    pub input_audio_tokens: Option<i64>,
    pub input_image_tokens: Option<i64>,
    pub output_text_tokens: Option<i64>,
    pub output_audio_tokens: Option<i64>,
    pub output_image_tokens: Option<i64>,
    pub reasoning_tokens: Option<i64>,
    pub cache_creation_5m_input_tokens: Option<i64>,
    pub cache_creation_1h_input_tokens: Option<i64>,
    pub usage_source: Option<String>,
    pub usage_semantic: Option<String>,
    pub service_tier: Option<String>,
    pub upstream_cost_mode: Option<String>,
    pub upstream_cost_source: Option<String>,
    pub upstream_price_per_request: Option<Decimal>,
    pub upstream_input_price_per_million: Option<Decimal>,
    pub upstream_output_price_per_million: Option<Decimal>,
    pub upstream_cache_creation_price_per_million: Option<Decimal>,
    pub upstream_cache_read_price_per_million: Option<Decimal>,
    pub upstream_request_cost: Option<Decimal>,
    pub upstream_input_cost: Option<Decimal>,
    pub upstream_output_cost: Option<Decimal>,
    pub upstream_cache_creation_cost: Option<Decimal>,
    pub upstream_cache_read_cost: Option<Decimal>,
    pub upstream_total_cost: Option<Decimal>,
    pub input_cost: Option<Decimal>,
    pub output_cost: Option<Decimal>,
    pub cache_creation_cost: Option<Decimal>,
    pub cache_read_cost: Option<Decimal>,
    pub request_cost: Option<Decimal>,
    pub input_price_per_million: Option<Decimal>,
    pub output_price_per_million: Option<Decimal>,
    pub cache_creation_price_per_million: Option<Decimal>,
    pub cache_read_price_per_million: Option<Decimal>,
    pub cost_currency: Option<String>,
    pub token_cost: Option<Decimal>,
    pub base_cost: Option<Decimal>,
    pub total_cost: Option<Decimal>,
    pub billing_multiplier: Option<Decimal>,
    pub billing_snapshot: Option<String>,
    pub response_headers_time_ms: Option<i64>,
    pub first_sse_event_time_ms: Option<i64>,
    pub first_output_time_ms: Option<i64>,
    pub first_byte_time_ms: Option<i64>,
    pub total_latency_ms: Option<i64>,
    pub candidate_count: i64,
    pub request_headers: Option<String>,
    pub request_body: Option<String>,
    pub client_response_headers: Option<String>,
    pub client_response_body: Option<String>,
    pub payload_compressed_at: Option<TimeDateTimeWithTimeZone>,
    pub created_at: TimeDateTimeWithTimeZone,
    pub started_at: Option<TimeDateTimeWithTimeZone>,
    pub finished_at: Option<TimeDateTimeWithTimeZone>,
    pub updated_at: TimeDateTimeWithTimeZone,
}

#[derive(Clone, Copy, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
