use rust_decimal::Decimal;

use crate::provider::{ProviderCooldownPolicy, ProviderSchedulingMode};

use super::{EmailSuffixMode, RequestRecordLevel, SmtpEncryption};

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct SystemSettings {
    pub site_name: String,
    pub site_subtitle: String,
    pub site_logo_base64: String,
    pub allow_registration: bool,
    pub login_captcha_enabled: bool,
    pub registration_captcha_enabled: bool,
    pub support_ticket_captcha_enabled: bool,
    pub registration_email_verification_enabled: bool,
    pub password_reset_enabled: bool,
    pub email_config_enabled: bool,
    pub support_ticket_email_notifications_enabled: bool,
    pub default_user_group_code: String,
    pub token_limit_per_user: i64,
    pub client_request_record_level: RequestRecordLevel,
    pub client_record_request_headers: bool,
    pub client_record_request_body: bool,
    pub client_record_response_headers: bool,
    pub client_record_response_body: bool,
    pub client_max_request_body_size_kb: i64,
    pub client_max_response_body_size_kb: i64,
    pub client_sensitive_request_headers: String,
    pub provider_request_record_level: RequestRecordLevel,
    pub provider_record_request_headers: bool,
    pub provider_record_request_body: bool,
    pub provider_record_response_headers: bool,
    pub provider_record_response_body: bool,
    pub provider_max_request_body_size_kb: i64,
    pub provider_max_response_body_size_kb: i64,
    pub provider_sensitive_request_headers: String,
    pub default_user_grant: Decimal,
    pub default_rate_limit_rpm: i64,
    pub recharge_enabled: bool,
    pub recharge_arrival_ratio: Decimal,
    pub recharge_order_expire_minutes: i64,
    pub recharge_min_amount: Decimal,
    pub recharge_max_amount: Decimal,
    pub scheduling_mode: ProviderSchedulingMode,
    pub cache_affinity_ttl_minutes: i64,
    pub provider_cooldown_policy: ProviderCooldownPolicy,
    pub smtp_host: String,
    pub smtp_port: i64,
    pub smtp_username: String,
    pub smtp_password_set: bool,
    pub smtp_from_email: String,
    pub smtp_from_name: String,
    pub smtp_encryption: SmtpEncryption,
    pub email_suffix_mode: EmailSuffixMode,
    pub email_suffixes: String,
    pub email_template_registration_subject: String,
    pub email_template_registration_html: String,
    pub email_template_password_reset_subject: String,
    pub email_template_password_reset_html: String,
    pub created_at: String,
    pub updated_at: String,
}
