import type { ProviderCooldownPolicy, ProviderSchedulingMode } from './provider';

export type RequestRecordLevel = 'basic' | 'headers' | 'full';
export type SmtpEncryption = 'none' | 'tls' | 'ssl';
export type EmailSuffixMode = 'none' | 'whitelist' | 'blacklist';

export type SystemSettings = {
  site_name: string;
  site_subtitle: string;
  public_base_url: string;
  site_logo_base64: string;
  allow_registration: boolean;
  login_captcha_enabled: boolean;
  registration_captcha_enabled: boolean;
  support_ticket_captcha_enabled: boolean;
  recharge_captcha_enabled: boolean;
  registration_email_verification_enabled: boolean;
  password_reset_enabled: boolean;
  email_config_enabled: boolean;
  support_ticket_email_notifications_enabled: boolean;
  default_user_group_code: string;
  token_limit_per_user: number;
  client_request_record_level: RequestRecordLevel;
  client_record_request_headers: boolean;
  client_record_request_body: boolean;
  client_record_response_headers: boolean;
  client_record_response_body: boolean;
  client_max_request_body_size_kb: number;
  client_max_response_body_size_kb: number;
  client_sensitive_request_headers: string;
  provider_request_record_level: RequestRecordLevel;
  provider_record_request_headers: boolean;
  provider_record_request_body: boolean;
  provider_record_response_headers: boolean;
  provider_record_response_body: boolean;
  provider_max_request_body_size_kb: number;
  provider_max_response_body_size_kb: number;
  provider_sensitive_request_headers: string;
  default_user_grant: number;
  default_rate_limit_rpm: number;
  recharge_enabled: boolean;
  recharge_arrival_ratio: number;
  recharge_order_expire_minutes: number;
  recharge_max_unpaid_orders: number;
  recharge_min_amount: number;
  recharge_max_amount: number;
  scheduling_mode: ProviderSchedulingMode;
  cache_affinity_ttl_minutes: number;
  provider_cooldown_policy: ProviderCooldownPolicy;
  smtp_host: string;
  smtp_port: number;
  smtp_username: string;
  smtp_password_set: boolean;
  smtp_from_email: string;
  smtp_from_name: string;
  smtp_encryption: SmtpEncryption;
  email_suffix_mode: EmailSuffixMode;
  email_suffixes: string;
  email_template_registration_subject: string;
  email_template_registration_html: string;
  email_template_password_reset_subject: string;
  email_template_password_reset_html: string;
  created_at: string;
  updated_at: string;
};

export type SystemSettingsUpdate = Partial<{
  site_name: string;
  site_subtitle: string;
  public_base_url: string;
  site_logo_base64: string;
  allow_registration: boolean;
  login_captcha_enabled: boolean;
  registration_captcha_enabled: boolean;
  support_ticket_captcha_enabled: boolean;
  recharge_captcha_enabled: boolean;
  registration_email_verification_enabled: boolean;
  password_reset_enabled: boolean;
  email_config_enabled: boolean;
  support_ticket_email_notifications_enabled: boolean;
  default_user_group_code: string;
  token_limit_per_user: number;
  client_request_record_level: RequestRecordLevel;
  client_record_request_headers: boolean;
  client_record_request_body: boolean;
  client_record_response_headers: boolean;
  client_record_response_body: boolean;
  client_max_request_body_size_kb: number;
  client_max_response_body_size_kb: number;
  client_sensitive_request_headers: string;
  provider_request_record_level: RequestRecordLevel;
  provider_record_request_headers: boolean;
  provider_record_request_body: boolean;
  provider_record_response_headers: boolean;
  provider_record_response_body: boolean;
  provider_max_request_body_size_kb: number;
  provider_max_response_body_size_kb: number;
  provider_sensitive_request_headers: string;
  default_user_grant: number;
  default_rate_limit_rpm: number;
  recharge_enabled: boolean;
  recharge_arrival_ratio: number;
  recharge_order_expire_minutes: number;
  recharge_max_unpaid_orders: number;
  recharge_min_amount: number;
  recharge_max_amount: number;
  scheduling_mode: ProviderSchedulingMode;
  cache_affinity_ttl_minutes: number;
  provider_cooldown_policy: ProviderCooldownPolicy;
  smtp_host: string;
  smtp_port: number;
  smtp_username: string;
  smtp_password: string;
  smtp_from_email: string;
  smtp_from_name: string;
  smtp_encryption: SmtpEncryption;
  email_suffix_mode: EmailSuffixMode;
  email_suffixes: string;
  email_template_registration_subject: string;
  email_template_registration_html: string;
  email_template_password_reset_subject: string;
  email_template_password_reset_html: string;
}>;

export type PublicSiteInfo = {
  site_name: string;
  site_subtitle: string;
  site_logo_base64: string;
};

export type SystemSettingsSmtpTestRequest = Partial<{
  smtp_host: string;
  smtp_port: number;
  smtp_username: string;
  smtp_password: string;
  smtp_from_email: string;
  smtp_from_name: string;
  smtp_encryption: SmtpEncryption;
}>;

export type SystemSettingsSmtpTestResponse = {
  success: boolean;
  message: string;
};
