use constants::user_group::DEFAULT_USER_GROUP_CODE;
use rust_decimal::Decimal;
use types::system_setting::{EmailSuffixMode, RequestRecordLevel, SmtpEncryption, SystemSettings};

pub(super) fn system_settings() -> SystemSettings {
    SystemSettings {
        site_name: "Hook".into(),
        site_subtitle: String::new(),
        public_base_url: "https://hook.test".into(),
        site_logo_base64: String::new(),
        contact_methods: Vec::new(),
        allow_registration: true,
        login_captcha_enabled: false,
        registration_captcha_enabled: false,
        support_ticket_captcha_enabled: false,
        recharge_captcha_enabled: false,
        registration_email_verification_enabled: false,
        auth_github_enabled: false,
        auth_github_client_id: String::new(),
        auth_github_client_secret_set: false,
        auth_google_enabled: false,
        auth_google_client_id: String::new(),
        auth_google_client_secret_set: false,
        auth_evm_enabled: false,
        auth_evm_chain_ids: "1".into(),
        auth_evm_statement: "Sign in to Hook".into(),
        password_reset_enabled: false,
        email_config_enabled: false,
        support_ticket_email_notifications_enabled: false,
        default_user_group_code: DEFAULT_USER_GROUP_CODE.into(),
        token_limit_per_user: 10,
        client_request_record_level: RequestRecordLevel::Basic,
        client_record_request_headers: false,
        client_record_request_body: false,
        client_record_response_headers: false,
        client_record_response_body: false,
        client_max_request_body_size_kb: 0,
        client_max_response_body_size_kb: 0,
        client_sensitive_request_headers: String::new(),
        provider_request_record_level: RequestRecordLevel::Basic,
        provider_record_request_headers: false,
        provider_record_request_body: false,
        provider_record_response_headers: false,
        provider_record_response_body: false,
        provider_max_request_body_size_kb: 0,
        provider_max_response_body_size_kb: 0,
        provider_sensitive_request_headers: String::new(),
        default_user_grant: Decimal::ZERO,
        default_rate_limit_rpm: 60,
        recharge_enabled: true,
        recharge_arrival_ratio: Decimal::new(7, 0),
        recharge_order_expire_minutes: 15,
        recharge_max_unpaid_orders: 5,
        recharge_min_amount: Decimal::new(1, 0),
        recharge_max_amount: Decimal::new(3000, 0),
        scheduling_mode: types::provider::ProviderSchedulingMode::FixedOrder,
        provider_priority_mode: types::provider::ProviderPriorityMode::Provider,
        key_priority_snapshot_initialized: false,
        cache_affinity_ttl_minutes: 60,
        provider_cooldown_policy: types::provider::ProviderCooldownPolicy::default(),
        smtp_host: String::new(),
        smtp_port: 587,
        smtp_username: String::new(),
        smtp_password_set: false,
        smtp_from_email: String::new(),
        smtp_from_name: String::new(),
        smtp_encryption: SmtpEncryption::Tls,
        email_suffix_mode: EmailSuffixMode::None,
        email_suffixes: String::new(),
        email_template_registration_subject: String::new(),
        email_template_registration_html: String::new(),
        email_template_password_reset_subject: String::new(),
        email_template_password_reset_html: String::new(),
        created_at: timestamp(),
        updated_at: timestamp(),
    }
}

fn timestamp() -> String {
    "2026-05-25T00:00:00Z".into()
}
