use sea_orm_migration::{prelude::*, schema::*};

use super::iden::{DashboardCostAnalysisBuckets, DashboardUserUsageBuckets, RequestCandidates, RequestRecords};

pub(super) fn request_records_table() -> TableCreateStatement {
    Table::create()
        .table(RequestRecords::Table)
        .if_not_exists()
        .col(string_len(RequestRecords::RequestId, 64).primary_key())
        .col(string_len_null(RequestRecords::TokenId, 36))
        .col(string_len_null(RequestRecords::UserIdSnapshot, 36))
        .col(string_len_null(RequestRecords::UsernameSnapshot, 100))
        .col(string_len_null(RequestRecords::TokenNameSnapshot, 100))
        .col(string_len_null(RequestRecords::TokenPrefixSnapshot, 32))
        .col(string_len_null(RequestRecords::GroupCode, 64))
        .col(string_len_null(RequestRecords::GlobalModelId, 36))
        .col(string_len_null(RequestRecords::ModelNameSnapshot, 100))
        .col(string_len_null(RequestRecords::ProviderId, 36))
        .col(string_len_null(RequestRecords::ProviderNameSnapshot, 100))
        .col(string_len_null(RequestRecords::EndpointId, 36))
        .col(string_len_null(RequestRecords::KeyId, 36))
        .col(string_len_null(RequestRecords::ProviderKeyNameSnapshot, 100))
        .col(string_len_null(RequestRecords::ProviderKeyPreviewSnapshot, 32))
        .col(string_len(RequestRecords::ClientApiFormat, 50))
        .col(string_len_null(RequestRecords::ProviderApiFormat, 50))
        .col(string_len(RequestRecords::RequestType, 40))
        .col(boolean(RequestRecords::IsStream))
        .col(boolean(RequestRecords::HasFailover))
        .col(boolean(RequestRecords::HasRetry))
        .col(string_len(RequestRecords::Status, 40))
        .col(string_len(RequestRecords::BillingStatus, 40))
        .col(integer_null(RequestRecords::ClientStatusCode))
        .col(string_len_null(RequestRecords::ClientErrorType, 100))
        .col(text_null(RequestRecords::ClientErrorMessage))
        .col(string_len_null(RequestRecords::TerminationOrigin, 60))
        .col(text_null(RequestRecords::TerminationReason))
        .col(string_len_null(RequestRecords::StreamEndReason, 60))
        .col(big_integer_null(RequestRecords::PromptTokens))
        .col(big_integer_null(RequestRecords::CompletionTokens))
        .col(big_integer_null(RequestRecords::TotalTokens))
        .col(big_integer_null(RequestRecords::CacheCreationInputTokens))
        .col(big_integer_null(RequestRecords::CacheReadInputTokens))
        .col(big_integer_null(RequestRecords::InputTextTokens))
        .col(big_integer_null(RequestRecords::InputAudioTokens))
        .col(big_integer_null(RequestRecords::InputImageTokens))
        .col(big_integer_null(RequestRecords::OutputTextTokens))
        .col(big_integer_null(RequestRecords::OutputAudioTokens))
        .col(big_integer_null(RequestRecords::OutputImageTokens))
        .col(big_integer_null(RequestRecords::ReasoningTokens))
        .col(big_integer_null(RequestRecords::CacheCreation5mInputTokens))
        .col(big_integer_null(RequestRecords::CacheCreation1hInputTokens))
        .col(string_len_null(RequestRecords::UsageSource, 40))
        .col(string_len_null(RequestRecords::UsageSemantic, 40))
        .col(string_len_null(RequestRecords::ServiceTier, 40))
        .col(string_len_null(RequestRecords::UpstreamCostMode, 20))
        .col(string_len_null(RequestRecords::UpstreamCostSource, 20))
        .col(decimal_len_null(RequestRecords::UpstreamPricePerRequest, 20, 8))
        .col(decimal_len_null(RequestRecords::UpstreamInputPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestRecords::UpstreamOutputPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestRecords::UpstreamCacheCreationPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestRecords::UpstreamCacheReadPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestRecords::UpstreamRequestCost, 20, 8))
        .col(decimal_len_null(RequestRecords::UpstreamInputCost, 20, 8))
        .col(decimal_len_null(RequestRecords::UpstreamOutputCost, 20, 8))
        .col(decimal_len_null(RequestRecords::UpstreamCacheCreationCost, 20, 8))
        .col(decimal_len_null(RequestRecords::UpstreamCacheReadCost, 20, 8))
        .col(decimal_len_null(RequestRecords::UpstreamTotalCost, 20, 8))
        .col(decimal_len_null(RequestRecords::InputCost, 20, 8))
        .col(decimal_len_null(RequestRecords::OutputCost, 20, 8))
        .col(decimal_len_null(RequestRecords::CacheCreationCost, 20, 8))
        .col(decimal_len_null(RequestRecords::CacheReadCost, 20, 8))
        .col(decimal_len_null(RequestRecords::RequestCost, 20, 8))
        .col(decimal_len_null(RequestRecords::InputPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestRecords::OutputPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestRecords::CacheCreationPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestRecords::CacheReadPricePerMillion, 20, 8))
        .col(string_len_null(RequestRecords::CostCurrency, 3))
        .col(decimal_len_null(RequestRecords::TokenCost, 20, 8))
        .col(decimal_len_null(RequestRecords::BaseCost, 20, 8))
        .col(decimal_len_null(RequestRecords::TotalCost, 20, 8))
        .col(decimal_len_null(RequestRecords::BillingMultiplier, 20, 8))
        .col(text_null(RequestRecords::BillingSnapshot))
        .col(big_integer_null(RequestRecords::ResponseHeadersTimeMs))
        .col(big_integer_null(RequestRecords::FirstSseEventTimeMs))
        .col(big_integer_null(RequestRecords::FirstTokenTimeMs))
        .col(big_integer_null(RequestRecords::FirstByteTimeMs))
        .col(big_integer_null(RequestRecords::TotalLatencyMs))
        .col(big_integer(RequestRecords::CandidateCount))
        .col(text_null(RequestRecords::RequestHeaders))
        .col(text_null(RequestRecords::RequestBody))
        .col(text_null(RequestRecords::ClientResponseHeaders))
        .col(text_null(RequestRecords::ClientResponseBody))
        .col(timestamp_tz_null(RequestRecords::PayloadCompressedAt))
        .col(timestamp_tz(RequestRecords::CreatedAt))
        .col(timestamp_tz_null(RequestRecords::StartedAt))
        .col(timestamp_tz_null(RequestRecords::FinishedAt))
        .col(timestamp_tz(RequestRecords::UpdatedAt))
        .to_owned()
}

pub(super) fn dashboard_user_usage_buckets_table() -> TableCreateStatement {
    Table::create()
        .table(DashboardUserUsageBuckets::Table)
        .if_not_exists()
        .col(string_len(DashboardUserUsageBuckets::Id, 36).primary_key())
        .col(string_len(DashboardUserUsageBuckets::BucketGranularity, 16))
        .col(timestamp_tz(DashboardUserUsageBuckets::BucketStartedAt))
        .col(timestamp_tz(DashboardUserUsageBuckets::BucketEndedAt))
        .col(string_len(DashboardUserUsageBuckets::UserId, 36))
        .col(string_len_null(DashboardUserUsageBuckets::Username, 100))
        .col(big_integer(DashboardUserUsageBuckets::RequestCount))
        .col(big_integer(DashboardUserUsageBuckets::SuccessCount))
        .col(big_integer(DashboardUserUsageBuckets::FailedCount))
        .col(big_integer(DashboardUserUsageBuckets::TotalTokens))
        .col(decimal_len(DashboardUserUsageBuckets::TotalCost, 20, 8))
        .col(big_integer(DashboardUserUsageBuckets::TotalLatencyMs))
        .col(big_integer(DashboardUserUsageBuckets::LatencySampleCount))
        .col(big_integer(DashboardUserUsageBuckets::ResponseHeadersTotalMs))
        .col(big_integer(DashboardUserUsageBuckets::ResponseHeadersSampleCount))
        .col(big_integer(DashboardUserUsageBuckets::FirstByteTotalMs))
        .col(big_integer(DashboardUserUsageBuckets::FirstByteSampleCount))
        .col(big_integer(DashboardUserUsageBuckets::FirstTokenTotalMs))
        .col(big_integer(DashboardUserUsageBuckets::FirstTokenSampleCount))
        .col(timestamp_tz(DashboardUserUsageBuckets::CreatedAt))
        .col(timestamp_tz(DashboardUserUsageBuckets::UpdatedAt))
        .index(
            Index::create()
                .name("index_dashboard_user_usage_buckets_unique")
                .col(DashboardUserUsageBuckets::BucketGranularity)
                .col(DashboardUserUsageBuckets::BucketStartedAt)
                .col(DashboardUserUsageBuckets::UserId)
                .unique(),
        )
        .to_owned()
}

pub(super) fn dashboard_cost_analysis_buckets_table() -> TableCreateStatement {
    Table::create()
        .table(DashboardCostAnalysisBuckets::Table)
        .if_not_exists()
        .col(string_len(DashboardCostAnalysisBuckets::Id, 36).primary_key())
        .col(timestamp_tz(DashboardCostAnalysisBuckets::BucketStartedAt))
        .col(timestamp_tz(DashboardCostAnalysisBuckets::BucketEndedAt))
        .col(string_len(DashboardCostAnalysisBuckets::DimensionKind, 24))
        .col(string_len(DashboardCostAnalysisBuckets::DimensionId, 100))
        .col(string_len_null(DashboardCostAnalysisBuckets::DimensionName, 120))
        .col(integer(DashboardCostAnalysisBuckets::Shard))
        .col(big_integer(DashboardCostAnalysisBuckets::RequestCount))
        .col(big_integer(DashboardCostAnalysisBuckets::SuccessCount))
        .col(big_integer(DashboardCostAnalysisBuckets::FailedCount))
        .col(big_integer(DashboardCostAnalysisBuckets::InputTokens))
        .col(big_integer(DashboardCostAnalysisBuckets::OutputTokens))
        .col(big_integer(DashboardCostAnalysisBuckets::CacheCreationTokens))
        .col(big_integer(DashboardCostAnalysisBuckets::CacheReadTokens))
        .col(big_integer(DashboardCostAnalysisBuckets::TotalTokens))
        .col(decimal_len(DashboardCostAnalysisBuckets::TotalCost, 20, 8))
        .col(decimal_len(DashboardCostAnalysisBuckets::UpstreamTotalCost, 20, 8))
        .col(decimal_len(DashboardCostAnalysisBuckets::CacheReadCost, 20, 8))
        .col(decimal_len(DashboardCostAnalysisBuckets::CacheCreationCost, 20, 8))
        .col(decimal_len(DashboardCostAnalysisBuckets::EstimatedFullCost, 20, 8))
        .col(big_integer(DashboardCostAnalysisBuckets::TotalLatencyMs))
        .col(big_integer(DashboardCostAnalysisBuckets::LatencySampleCount))
        .col(big_integer(DashboardCostAnalysisBuckets::ResponseHeadersTotalMs))
        .col(big_integer(DashboardCostAnalysisBuckets::ResponseHeadersSampleCount))
        .col(big_integer(DashboardCostAnalysisBuckets::FirstByteTotalMs))
        .col(big_integer(DashboardCostAnalysisBuckets::FirstByteSampleCount))
        .col(big_integer(DashboardCostAnalysisBuckets::FirstSseEventTotalMs))
        .col(big_integer(DashboardCostAnalysisBuckets::FirstSseEventSampleCount))
        .col(big_integer(DashboardCostAnalysisBuckets::FirstTokenTotalMs))
        .col(big_integer(DashboardCostAnalysisBuckets::FirstTokenSampleCount))
        .col(big_integer(DashboardCostAnalysisBuckets::SseToOutputTotalMs))
        .col(big_integer(DashboardCostAnalysisBuckets::SseToOutputSampleCount))
        .col(timestamp_tz(DashboardCostAnalysisBuckets::CreatedAt))
        .col(timestamp_tz(DashboardCostAnalysisBuckets::UpdatedAt))
        .index(
            Index::create()
                .name("index_dashboard_cost_analysis_buckets_unique")
                .col(DashboardCostAnalysisBuckets::BucketStartedAt)
                .col(DashboardCostAnalysisBuckets::DimensionKind)
                .col(DashboardCostAnalysisBuckets::DimensionId)
                .col(DashboardCostAnalysisBuckets::Shard)
                .unique(),
        )
        .to_owned()
}

pub(super) fn request_candidates_table() -> TableCreateStatement {
    Table::create()
        .table(RequestCandidates::Table)
        .if_not_exists()
        .col(string_len(RequestCandidates::Id, 36).primary_key())
        .col(string_len(RequestCandidates::RequestId, 64))
        .col(string_len_null(RequestCandidates::TokenId, 36))
        .col(string_len_null(RequestCandidates::GroupCode, 64))
        .col(string_len_null(RequestCandidates::GlobalModelId, 36))
        .col(string_len_null(RequestCandidates::ProviderId, 36))
        .col(string_len_null(RequestCandidates::ProviderNameSnapshot, 100))
        .col(string_len_null(RequestCandidates::EndpointId, 36))
        .col(string_len_null(RequestCandidates::EndpointNameSnapshot, 50))
        .col(string_len_null(RequestCandidates::KeyId, 36))
        .col(string_len_null(RequestCandidates::KeyNameSnapshot, 100))
        .col(string_len_null(RequestCandidates::KeyPreviewSnapshot, 32))
        .col(string_len(RequestCandidates::ClientApiFormat, 50))
        .col(string_len_null(RequestCandidates::ProviderApiFormat, 50))
        .col(boolean(RequestCandidates::NeedsConversion))
        .col(boolean(RequestCandidates::IsStream))
        .col(boolean(RequestCandidates::IsCached))
        .col(text_null(RequestCandidates::ProviderRequestHeaders))
        .col(text_null(RequestCandidates::ProviderRequestBody))
        .col(text_null(RequestCandidates::ProviderResponseHeaders))
        .col(text_null(RequestCandidates::ProviderResponseBody))
        .col(timestamp_tz_null(RequestCandidates::PayloadCompressedAt))
        .col(integer(RequestCandidates::CandidateIndex))
        .col(integer(RequestCandidates::RetryIndex))
        .col(string_len(RequestCandidates::Status, 40))
        .col(text_null(RequestCandidates::SkipReason))
        .col(integer_null(RequestCandidates::StatusCode))
        .col(big_integer_null(RequestCandidates::PromptTokens))
        .col(big_integer_null(RequestCandidates::CompletionTokens))
        .col(big_integer_null(RequestCandidates::TotalTokens))
        .col(big_integer_null(RequestCandidates::CacheCreationInputTokens))
        .col(big_integer_null(RequestCandidates::CacheReadInputTokens))
        .col(big_integer_null(RequestCandidates::InputTextTokens))
        .col(big_integer_null(RequestCandidates::InputAudioTokens))
        .col(big_integer_null(RequestCandidates::InputImageTokens))
        .col(big_integer_null(RequestCandidates::OutputTextTokens))
        .col(big_integer_null(RequestCandidates::OutputAudioTokens))
        .col(big_integer_null(RequestCandidates::OutputImageTokens))
        .col(big_integer_null(RequestCandidates::ReasoningTokens))
        .col(big_integer_null(RequestCandidates::CacheCreation5mInputTokens))
        .col(big_integer_null(RequestCandidates::CacheCreation1hInputTokens))
        .col(string_len_null(RequestCandidates::UsageSource, 40))
        .col(string_len_null(RequestCandidates::UsageSemantic, 40))
        .col(string_len_null(RequestCandidates::ServiceTier, 40))
        .col(string_len_null(RequestCandidates::UpstreamCostMode, 20))
        .col(string_len_null(RequestCandidates::UpstreamCostSource, 20))
        .col(decimal_len_null(RequestCandidates::UpstreamPricePerRequest, 20, 8))
        .col(decimal_len_null(RequestCandidates::UpstreamInputPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestCandidates::UpstreamOutputPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestCandidates::UpstreamCacheCreationPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestCandidates::UpstreamCacheReadPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestCandidates::UpstreamRequestCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::UpstreamInputCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::UpstreamOutputCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::UpstreamCacheCreationCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::UpstreamCacheReadCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::UpstreamTotalCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::InputCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::OutputCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::CacheCreationCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::CacheReadCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::RequestCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::InputPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestCandidates::OutputPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestCandidates::CacheCreationPricePerMillion, 20, 8))
        .col(decimal_len_null(RequestCandidates::CacheReadPricePerMillion, 20, 8))
        .col(string_len_null(RequestCandidates::CostCurrency, 3))
        .col(decimal_len_null(RequestCandidates::TokenCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::BaseCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::TotalCost, 20, 8))
        .col(decimal_len_null(RequestCandidates::BillingMultiplier, 20, 8))
        .col(text_null(RequestCandidates::BillingSnapshot))
        .col(big_integer_null(RequestCandidates::LatencyMs))
        .col(big_integer_null(RequestCandidates::ResponseHeadersTimeMs))
        .col(big_integer_null(RequestCandidates::FirstSseEventTimeMs))
        .col(big_integer_null(RequestCandidates::FirstTokenTimeMs))
        .col(big_integer_null(RequestCandidates::FirstByteTimeMs))
        .col(string_len_null(RequestCandidates::ErrorType, 100))
        .col(text_null(RequestCandidates::ErrorMessage))
        .col(text_null(RequestCandidates::ErrorCode))
        .col(string_len_null(RequestCandidates::ErrorParam, 160))
        .col(timestamp_tz(RequestCandidates::CreatedAt))
        .col(timestamp_tz_null(RequestCandidates::StartedAt))
        .col(timestamp_tz_null(RequestCandidates::FinishedAt))
        .to_owned()
}

fn integer<T>(col: T) -> ColumnDef
where
    T: IntoIden,
{
    ColumnDef::new(col).integer().not_null().take()
}

fn integer_null<T>(col: T) -> ColumnDef
where
    T: IntoIden,
{
    ColumnDef::new(col).integer().null().take()
}

fn timestamp_tz<T>(col: T) -> ColumnDef
where
    T: IntoIden,
{
    ColumnDef::new(col).timestamp_with_time_zone().not_null().take()
}

fn timestamp_tz_null<T>(col: T) -> ColumnDef
where
    T: IntoIden,
{
    ColumnDef::new(col).timestamp_with_time_zone().null().take()
}
